FROM gradle:7.4.2-jdk17 AS build

COPY . /src

WORKDIR /src

RUN gradle :api-service:build -x test --no-daemon

FROM openjdk:17-alpine

LABEL description="This service is part of E2E-tests implementation example. Check out repository for more details https://github.com/SimonHarmonicMinor/e2e-tests-example"

RUN mkdir /app

COPY --from=build /src/api-service/build/libs/api-service-0.0.1-SNAPSHOT.jar /app/application.jar

EXPOSE 8080

CMD ["java", "-jar", "/app/application.jar"]